### ISSUE TITLE
Don't expect Modifier parameters on Preview functions

### ISSUE THREAD

**Issue by ZacSweers** [slackhq/compose-lints#377]

**Comment by yukilabo** [comment]
In our project, we are experiencing the following problem. Does this Issue point out something similar?

```
// These are annotated with @Preview.
@DeviceWidthPreviews
@ThemePreviews
annotation class ComponentPreviews

// "TestPreview"  is a preview function, but Lint says "There is no modifier".
@ComponentPreviews
@Composable
private fun TestPreview() {
    Text(text = "Hello, World!")
}
```

I think this is because [isPreview](https://github.com/slackhq/compose-lints/blob/main/compose-lint-checks/src/main/java/slack/lint/compose/util/Previews.kt#L14) only checks if the function's annotation has `@Preview` attached to it.
